### ISSUE TITLE
"Using the 'onlinegmmdecodefaster' based worker"

### ISSUE THREAD

**Issue by Alif112** [alumae/kaldi-gstreamer-server#112]
i have tried this and got the same type of problem in decoder. and i am trying: "Using the 'onlinegmmdecodefaster' based worker"

python kaldigstserver/worker.py -u ws://localhost:8888/worker/ws/speech -c sample_english_nnet2.yaml

DEBUG 2018-01-28 12:35:12,871 Starting up worker
2018-01-28 12:35:12 - INFO: decoder2: Creating decoder using conf: {'post-processor': "perl -npe 'BEGIN {use IO::Handle; STDOUT->autoflush(1);} s/(.*)/\1./;'", 'logging': {'version': 1, 'root': {'level': 'DEBUG', 'handlers': ['console']}, 'formatters': {'simpleFormater': {'datefmt': '%Y-%m-%d %H:%M:%S', 'format': '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s'}}, 'disable_existing_loggers': False, 'handlers': {'console': {'formatter': 'simpleFormater', 'class': 'logging.StreamHandler', 'level': 'DEBUG'}}}, 'use-nnet2': True, 'full-post-processor': './sample_full_post_processor.py', 'decoder': {'ivector-extraction-config': 'test/models/english/tedlium_nnet_ms_sp_online/conf/ivector_extractor.conf', 'num-nbest': 10, 'lattice-beam': 6.0, 'acoustic-scale': 0.083, 'do-endpointing': True, 'beam': 10.0, 'max-active': 10000, 'fst': 'test/models/english/tedlium_nnet_ms_sp_online/HCLG.fst', 'mfcc-config': 'test/models/english/tedlium_nnet_ms_sp_online/conf/mfcc.conf', 'use-threaded-decoder': True, 'traceback-period-in-secs': 0.25, 'model': 'test/models/english/tedlium_nnet_ms_sp_online/final.mdl', 'word-syms': 'test/models/english/tedlium_nnet_ms_sp_online/words.txt', 'endpoint-silence-phones': '1:2:3:4:5:6:7:8:9:10', 'chunk-length-in-secs': 0.25}, 'silence-timeout': 10, 'out-dir': 'tmp', 'use-vad': False}
Traceback (most recent call last):
File "kaldigstserver/worker.py", line 366, in 
main()
File "kaldigstserver/worker.py", line 346, in main
decoder_pipeline = DecoderPipeline2(conf)
File "/media/thesis/73EF5F223191438D/kaldi-gstreamer-server/kaldigstserver/decoder2.py", line 24, in init
self.create_pipeline(conf)
File "/media/thesis/73EF5F223191438D/kaldi-gstreamer-server/kaldigstserver/decoder2.py", line 53, in create_pipeline
self.asr.set_property("use-threaded-decoder", conf["decoder"]["use-threaded-decoder"])
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by madacol** [comment]
cd into kaldi's folder and build gst-plugin, it should go something like this:
```
cd ~/kaldi/src/gst-plugin
make depend; make
```
and don't forget to add `export GST_PLUGIN_PATH=~/kaldi/src/gst-plugin`

**Comment by Alif112** [comment]
thanks
