### ISSUE TITLE
Worker error 

### ISSUE THREAD

**Issue by jazzystring1** [alumae/kaldi-gstreamer-server#133]
I had setup the worker and server and it works fine but when i send audio via the HTTP api, 

      ` curl  -T test/data/english_test.wav  "http://localhost:8888/client/dynamic/recognize"`

the workers gives error. Here is the worker logs:

```
2018-05-19 00:51:10 -   DEBUG:   __main__: <undefined>: Got message from server of type <class 'ws4py.messaging.TextMessage'>
2018-05-19 00:51:10 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Pipeline initialized
2018-05-19 00:51:10 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Started timeout guard
2018-05-19 00:51:10 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Initialized request
2018-05-19 00:51:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
2018-05-19 00:51:10 -   DEBUG:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Pushing buffer of size 16384 to pipeline
2018-05-19 00:51:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
2018-05-19 00:51:10 -   DEBUG:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Pushing buffer of size 49152 to pipeline
2018-05-19 00:51:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
2018-05-19 00:51:10 -   DEBUG:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Pushing buffer of size 65536 to pipeline
2018-05-19 00:51:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
2018-05-19 00:51:10 -   DEBUG:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Pushing buffer of size 65536 to pipeline
2018-05-19 00:51:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
2018-05-19 00:51:10 -   DEBUG:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Pushing buffer of size 44 to pipeline
2018-05-19 00:51:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
2018-05-19 00:51:10 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Pushing EOS to pipeline
2018-05-19 00:51:10 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Connecting audio decoder
2018-05-19 00:51:10 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Connected audio decoder
2018-05-19 00:51:11 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:12 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:13 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:13 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: ONE
2018-05-19 00:51:13 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:13 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Starting postprocessing: ONE
2018-05-19 00:51:13 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing returned: ONE.

2018-05-19 00:51:13 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing done.
2018-05-19 00:51:13 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: TWO
2018-05-19 00:51:13 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:13 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Starting postprocessing: ONE TWO
2018-05-19 00:51:13 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing returned: ONE TWO.

2018-05-19 00:51:13 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing done.
2018-05-19 00:51:13 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: THREE
2018-05-19 00:51:13 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:13 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Starting postprocessing: ONE TWO THREE
2018-05-19 00:51:14 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:15 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: FOUR
2018-05-19 00:51:15 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:15 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Skipping postprocessing since post-processor already in use
2018-05-19 00:51:15 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: FIVE
2018-05-19 00:51:15 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:15 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Skipping postprocessing since post-processor already in use
2018-05-19 00:51:15 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: SIX
2018-05-19 00:51:15 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:15 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Skipping postprocessing since post-processor already in use
2018-05-19 00:51:15 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:16 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: SEVEN
2018-05-19 00:51:16 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:16 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Skipping postprocessing since post-processor already in use
2018-05-19 00:51:16 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: EIGHT
2018-05-19 00:51:16 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing partial result..
2018-05-19 00:51:16 -   ERROR: tornado.application: Future exception was never retrieved: Traceback (most recent call last):
  File "/home/cdj/.local/lib/python2.7/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "kaldigstserver/worker.py", line 247, in _on_word
    processed_transcript = (yield self.post_process([self.partial_transcript], blocking=False))[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-05-19 00:51:16 -   ERROR: tornado.application: Future exception was never retrieved: Traceback (most recent call last):
  File "/home/cdj/.local/lib/python2.7/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "kaldigstserver/worker.py", line 247, in _on_word
    processed_transcript = (yield self.post_process([self.partial_transcript], blocking=False))[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-05-19 00:51:16 -   ERROR: tornado.application: Future exception was never retrieved: Traceback (most recent call last):
  File "/home/cdj/.local/lib/python2.7/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "kaldigstserver/worker.py", line 247, in _on_word
    processed_transcript = (yield self.post_process([self.partial_transcript], blocking=False))[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-05-19 00:51:16 -   ERROR: tornado.application: Future exception was never retrieved: Traceback (most recent call last):
  File "/home/cdj/.local/lib/python2.7/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "kaldigstserver/worker.py", line 247, in _on_word
    processed_transcript = (yield self.post_process([self.partial_transcript], blocking=False))[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-05-19 00:51:16 -   DEBUG:       root: 9020a33f-118d-4bac-b5f7-84967f5393f5: Skipping postprocessing since post-processor already in use
2018-05-19 00:51:16 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Got word: <#s>
2018-05-19 00:51:16 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Postprocessing final result..
2018-05-19 00:51:16 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:17 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:18 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:19 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:20 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:21 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:22 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:23 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:24 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:25 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:26 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:27 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:28 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:29 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:30 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:31 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:32 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:33 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:34 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:35 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:36 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:37 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:38 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:39 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:40 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:41 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:42 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:43 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:44 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:45 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:46 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:47 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:48 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:49 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:50 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:51 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:52 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:53 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:54 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:55 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:56 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:57 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:58 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:51:59 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:00 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:01 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:02 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:03 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:04 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:05 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:06 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:07 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:08 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:09 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:10 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:11 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:12 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:13 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:14 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:15 -   DEBUG:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Checking that decoder hasn't been silent for more than 60 seconds
2018-05-19 00:52:16 - WARNING:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: More than 60 seconds from last decoder hypothesis update, cancelling
2018-05-19 00:52:16 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Master disconnected before decoder reached EOS?
2018-05-19 00:52:16 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Cancelling pipeline
2018-05-19 00:52:16 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Cancelled pipeline
2018-05-19 00:52:16 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:17 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:18 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:19 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:20 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:21 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:22 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:23 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:24 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:25 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:26 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:27 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:28 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:29 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:30 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:31 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:32 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:33 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:34 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:35 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:36 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:37 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:38 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:39 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:40 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:41 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:42 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:43 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:44 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:45 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Waiting for EOS from decoder
2018-05-19 00:52:46 -    INFO:   __main__: 9020a33f-118d-4bac-b5f7-84967f5393f5: Giving up waiting after 31 tries
2018-05-19 00:52:46 -    INFO:    decoder: 9020a33f-118d-4bac-b5f7-84967f5393f5: Finishing request
```
afterwards, Python 2.7 crashes unexpectedly.

**Comment by yfchen1994** [comment]
I met with the same problem... :(

**Comment by ndri** [comment]
Same here :(
