### ISSUE TITLE
http api not working for raw audio files

### ISSUE THREAD

**Issue by krupalkp97** [alumae/kaldi-gstreamer-server#218]
Hello
         i am using the librispeech pre trained model for my application . It is working fine with wav file but when i try to pass a raw audio file it fails and gives error.

the command that i am trying 
`curl -v -T test/data/english_test.raw -H "Content-Type: audio/x-raw-int; rate=16000" --header "Transfer-Encoding: chunked" --limit-rate 32000  "http://localhost:8888/client/dynamic/recognize"`

the error it is giving
 >` Trying 127.0.0.1...
>* TCP_NODELAY set
>* Connected to localhost (127.0.0.1) port 8888 (#0)
> PUT /client/dynamic/recognize HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: audio/x-raw-int; rate=16000
> Transfer-Encoding: chunked
> Expect: 100-continue
> 
>< HTTP/1.1 500 Internal Server Error
>< Server: TornadoServer/4.5.3
>< Content-Type: text/html; charset=UTF-8
>< Date: Mon, 25 Nov 2019 11:03:27 GMT
>< Content-Length: 93
>* HTTP error before end of send, stop sending
>* Closing connection 0
><html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>`

and the error displayed in master server 
`   ERROR 2019-11-25 16:33:27,955 Uncaught exception PUT /client/dynamic/recognize (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='PUT', uri='/client/dynamic/recognize', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8888', 'User-Agent': 'curl/7.58.0', 'Accept': '*/*', 'Content-Type': 'audio/x-raw-int; rate=16000', 'Transfer-Encoding': 'chunked', 'Expect': '100-continue'}) 
Traceback (most recent call last):
  File "/home/krupal/Documents/KALDI_GS_SERVER/.gs/lib/python3.6/site-packages/tornado/web.py", line 1489, in _execute
    result = self.prepare()
  File "kaldigstserver/master_server.py", line 126, in prepare
    content_type = content_type_to_caps(content_type)
  File "kaldigstserver/master_server.py", line 94, in content_type_to_caps
    return "%s, %s" % (media_type, ", ".join(["%s=%s" % (key, value) for (key,value) in attributes.iteritems()]))
AttributeError: 'dict' object has no attribute 'iteritems'
   ERROR 2019-11-25 16:33:27,976 500 PUT /client/dynamic/recognize (127.0.0.1) 22.12ms` 

I am new at using kaldi as well as Gstreamer , so can you help me with this issue and guide me what am i doing wrong 

Thanks in advance

**Comment by alumae** [comment]
I think it's because you need to run the server using Python 2.7, but you are probably using Python 3+

**Comment by krupalkp97** [comment]
Thank you for the quick response i will try to change the code  as per the python requirement. 

one more quick question how can i reduce the time taken in response (under 1 or 2 second)
