### ISSUE TITLE
error when run "worker"

### ISSUE THREAD

**Issue by xiechen0692** [alumae/kaldi-gstreamer-server#228]
Hi, thanks for you open source the code. I follow the step in README.
everything goes well and I can run "gst-inspect-1.0 onlinegmmdecodefaster".
error after I run "python kaldigstserver/worker.py -u ws://localhost:8888/worker/ws/sp
eech -c sample_worker.yaml"

**error:
"""Traceback (most recent call last):
  File "kaldigstserver/worker.py", line 28, in <module>
    from decoder import DecoderPipeline
  File "/home/classiii/xiechen/kaldi-gstreamer-server-master/kaldigstserver/decoder.py", line 8, in <module>
    gi.require_version('Gst', '1.0')
  File "/home/classiii/anaconda3/envs/kaldiserver/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available""""**

Is it the reason for gst version? I use gst 1.0 follow this command "sudo apt-get install libgstreamer1.0-dev gstreamer1.0-plugins-good gstreamer1.0-tools gstreamer1.0-pulseaudio".
Looking forward for your answer! Thanks a lot!

**Comment by zrsjta** [comment]
Totally the same problem. Have you solved it? Thx

**Comment by ugrozkr** [comment]
I get same error too. Can anyone help us ?

**Comment by sungyihsun** [comment]
me too same error , Have you solved it? pls. help Thanks you .

**Comment by xiechen0692** [comment]
I have not soloved it yet..

**Comment by minhduc0711** [comment]
I got the same error (on py3 branch) when I install `pygobject` using `conda install -c conda-forge pygobject`.
So I tried using `pip` instead and it worked
```
# pygobject build dependencies
apt install libcairo2-dev libgirepository1.0-dev 
pip install pygobject
```
Hope this helps you guys.
