### ISSUE TITLE
Error when running python kaldigstserver/worker.py on sample chinese

### ISSUE THREAD

**Issue by RobertLevenbach** [alumae/kaldi-gstreamer-server#245]
Hello everyone,

I'm trying to run kaldigstserver/worker.py on the sample chinese model. I get the following error (on python 2.7 and python 3.7) 

How can this be fixed and why does this happen?

~/mic/gstreamer$ python3 kaldigstserver/worker.py -u ws://localhost:8888/worker/ws/speech -c sample_chinese_nnet3.yaml
2020-10-14 17:38:08 -   DEBUG:    asyncio: Using selector: EpollSelector
2020-10-14 17:38:08 -    INFO:   decoder2: Creating decoder using conf: {'use-nnet2': True, 'decoder': {'nnet-mode': 3, 'use-threaded-decoder': True, 'model': 'test/models/chinese/multi_cn_chain_sp_online/final.mdl', 'word-syms': 'test/models/chinese/multi_cn_chain_sp_online/words.txt', 'fst': 'test/models/chinese/multi_cn_chain_sp_online/HCLG.fst', 'mfcc-config': 'test/models/chinese/multi_cn_chain_sp_online/conf/mfcc.conf', 'ivector-extraction-config': 'test/models/chinese/multi_cn_chain_sp_online/conf/ivector_extractor.conf', 'max-active': 7000, 'beam': 15.0, 'lattice-beam': 6.0, 'acoustic-scale': 1.0, 'do-endpointing': True, 'endpoint-silence-phones': '1:2:3:4:5:6:7:8:9:10:11:12:13:14:15', 'traceback-period-in-secs': 0.25, 'chunk-length-in-secs': 0.25, 'num-nbest': 1}, 'out-dir': 'tmp', 'use-vad': False, 'silence-timeout': 10, 'post-processor': "perl -npe 'BEGIN {use IO::Handle; STDOUT->autoflush(1);} sleep(1); s/(.*)/\\1./;'", 'logging': {'version': 1, 'disable_existing_loggers': False, 'formatters': {'simpleFormater': {'format': '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s', 'datefmt': '%Y-%m-%d %H:%M:%S'}}, 'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'simpleFormater', 'level': 'DEBUG'}}, 'root': {'level': 'DEBUG', 'handlers': ['console']}}}
Traceback (most recent call last):
  File "kaldigstserver/worker.py", line 425, in <module>
    main()
  File "kaldigstserver/worker.py", line 414, in main
    decoder_pipeline = DecoderPipeline2(conf)
  File "/home/robert/mic/gstreamer/kaldigstserver/decoder2.py", line 26, in __init__
    self.create_pipeline(conf)
  File "/home/robert/mic/gstreamer/kaldigstserver/decoder2.py", line 55, in create_pipeline
    print >> sys.stderr, "ERROR: Couldn't create the kaldinnet2onlinedecoder element!"
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?

**Comment by YichiHuang** [comment]
pull the update Kaldi version and recompile. It might be caused by wrong Kaldi version.
