### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'binary_message

### ISSUE THREAD

**Issue by AshStuff** [alumae/kaldi-gstreamer-server#67]
```
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/e/ashwinraju/kaldi_asr/asr/py-kaldi/tests/client.py", line 58, in send_data_to_ws
    self.send_data(block)
  File "/e/ashwinraju/kaldi_asr/asr/py-kaldi/tests/client.py", line 22, in rate_limited_function
    ret = func(*args,**kargs)
  File "/e/ashwinraju/kaldi_asr/asr/py-kaldi/tests/client.py", line 43, in send_data
    self.send(data, binary=True)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 257, in send
    message_sender = self.stream.binary_message if binary else self.stream.text_message
AttributeError: 'NoneType' object has no attribute 'binary_message
```
I am calculating predictions for a list of test samples in a multiprocessing way. I am able to predict the output but still am gettting this AttributeError . Any idea to avoid this error.

**Comment by alumae** [comment]
Please clarify your issue. It's difficult to understand where and when this problem occurs.

**Comment by alejandro-pnz** [comment]
Does anyone solves this problem?

**Comment by wujsy** [comment]
@Alif112  Do you have sloved this problem?

**Comment by Alif112** [comment]
@wujsy its long time ago, i dont remember much, but i would like to assure u that using docker will help u a lot. And docker image was bug free.
